### ISSUE TITLE
Could it have a 1.18.2 version?please

### ISSUE THREAD

**Issue by Zhangyide114514** [Avanatiker/WorldTools#27] opened 2024-04-15 03:13 UTC
Pokechu22/WorldDownloader only supports up to 1.16.5
But this only 1.20.1
Please,I believe many people still need a mod for version 1.18.2 just like me :(

**Comment by dumbasPL** [comment] 2024-04-22 08:26
duplicate of #23

**Closed** 2024-04-22 21:31 UTC
